### ISSUE TITLE
graph display bug

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-client#23]
@mehrdadgit notes overlapping text on graph
![messages image 3791766982](https://user-images.githubusercontent.com/2288238/49919212-e9587380-fef9-11e8-905a-f09caaf094c8.jpeg)

**Comment by mehrdadgit** [comment]
Just realised this happens where there are multiple arcs(edge) between two nodes...Sigma.js does not seem to support multiple edge between 2 nodes ? 
If so we should consider using another visualisation library ...or including only exactly one edge in data ?

**Comment by matthewberryman** [comment]
Even if you just have one edge, it's possible to fill this up with too much text. Happy to look for react alternatives (e.g. the d3 one) but ideally one with typescript definitions already written.

**Comment by mehrdadgit** [comment]
The bug is fixed now with a work-around using the existing sigma-js :) note it is in its own branch (whose parent branch is map_view )

Did a lot of digging for graphing libraries based react, d3 etc, most of them, having better interactivity IMO,  do not support label for graph edges, e.g. ttps://github.com/danielcaldas/react-d3-graph (or they do but not readily in react /TS) ... I suggest closing this one after merge; later we can work on changing the visualisation framework if needed.
